### ISSUE TITLE
Make option delimiter 

### ISSUE THREAD

**Issue by NamPNQ** [angular-ui/ui-mention#24]
Make delimiter configuarable instead `@`

**Comment by ProLoser** [comment]
Change the controller's `delimiter` property.

**Comment by NamPNQ** [comment]
This is not enought, change character @ in search.indexOf in function `replace`

**Comment by ProLoser** [comment]
Yeah you're right.

If someone wants to submit a PR, 

[this line](https://github.com/angular-ui/ui-mention/blob/master/src/mentionController.es6.js#L162) should be made an option similar to [this.pattern](https://github.com/angular-ui/ui-mention/blob/master/src/mentionController.es6.js#L7) (I actually don't know if we need the `x = x | y` instead of just `x = y`.

I'm also curious if [this.decode](https://github.com/angular-ui/ui-mention/blob/master/src/mentionController.es6.js#L122) should be changed to use `this.pattern`. Finally, I'm wondering if we should soft-code all instances of the trigger token (for instance, in the regex patterns and [this.encode](https://github.com/angular-ui/ui-mention/blob/master/src/mentionController.es6.js#L146))

**Comment by biggieman** [comment]
I made a Pull Request and I think this is the easiest way to do it with backward compatibility
