### ISSUE TITLE
Allow for '_id' for Mongo users

### ISSUE THREAD

**Issue by bighitbiker3** [angular-ui/ui-mention#33]
Thanks so much for making this! It's working great for us. However one thing - when using MongoDB the `choice.id` will be undefined for data being returned from our db.  Right now we're forced to using a computed property in our JS-Data implementation to add an `id` field.  

Would be nice if the `this.encode` function looked like this:

```
  this.encode = function (choice) {
    return '@[' + this.label(choice) + ':' + choice.id || choice._id + ']';
  };
```

Would you accept a PR for this?

**Comment by ProLoser** [comment]
No. The point of the library is it's so simple that you should be able to hack on it. Think of the controller like a base class. You should just extend it and override the method with your own implementation. That's why all the methods are publicly exposed. What you describe is super duper specific to your own implementation.

Unfortunately, I don't have a super streamlined way to do this outside of what's illustrated in the docs.

**Comment by bighitbiker3** [comment]
@ProLoser Makes sense...thanks again
